image: docker:24.0.5

services:
  - name: docker:24.0.5-dind
    alias: docker

variables:
  # Voorkom TLS problemen met DinD
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""   # Disable TLS since we're in a secure environment
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: "true"  # Gebruik een uniek netwerk per build
  DOCKER_BUILDKIT: "1"  # Enable BuildKit voor betere prestaties

stages:
  - ansible

ansible-playbook:
  stage: ansible
  image: quay.io/ansible/ansible-runner:latest
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ansible-playbook -i inventory playbook.yml
  only:
    - main
